### ISSUE TITLE
Error installing

### ISSUE THREAD

**Issue by benheb** [cambecc/grib2json#1]
Running mvn packing is throwing an error an the build is failing. Looks like an invalid target release. Where can I update/change? 

Error: https://gist.github.com/benheb/68800cc4de358cbeb331

**Comment by Jamos1988** [comment]
I have the same error, my java version is:

openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.8+10-post-Raspbian-1deb10u1, mixed mode)
