### ISSUE TITLE
OSCAR netcdf to JSON conversion?

### ISSUE THREAD

**Issue by prasanjitdash** [cambecc/grib2json#38]
The utility tool is really helpful and saves a lot of time, Many Thanks for this.

The `grib2json` instruction is very clear:
`grib2json --names --data --fp 2 --fs 103 --fv 10.0 gfs.t18z.pgrbf00.2p5deg.grib2`

However, the instruction for converting OSCAR nc files to JSON is kind of missing. How can one specify OSCAR netcdf files available from [https://podaac.jpl.nasa.gov/dataset/OSCAR_L4_OC_third-deg](url) as input to the CLI?
`grib2json --names --data --fp 2 --fs 103 --fv 10.0 <input_oscar_file.nc>` ?

Thanks

**Comment by prasanjitdash** [comment]
Well, I figured it out. It was simple and the command specification is exactly the same as for grib2 files. I am closing the (non-)issue but keeping the answer if someone else needs it.

Here are some pointers:

(1) OSCAR Data Download: [https://podaac-tools.jpl.nasa.gov/drive/files/allData/oscar/preview/L4/oscar_third_deg](url)
You will now need to register an account with JPL PODAAC on EarthData.

In case you are confused with the fileName:  The files are updated every 5 days and filename has a number denoting 'days since 1992 ...sometime'.

(2) Using grib2json in Linux bash:
```
thisLocalNCfile=$INPUT_PATH/oscar_vel9943.nc
thisLocalJSONfile=$OUTPUT_PATH/oscar_vel9943.json
grib2json -d -c -n -o ${thisLocalJSONfile} ${thisLocalNCfile}
```

**Comment by Anik-Bardhan** [comment]
@prasanjitdash Hey. I keep running into java.lang.NullPointerException when running this command. Any kind of help regarding this will be of great value. Thanks.

**Comment by prasanjitdash** [comment]
Its been a while and I have forgotten the specifics and I am no JAVA expert, but what have you tried exactly? OSCAR or GFS?

The code, to what I recall, is kind of hard-coded and calls either 'OscarRecordWriter.java' or 'GribRecordWriter.java' and for data other than OSCAR and GFS, I had to modify the code.

Provide some specifics and I will try to revisit.

Also, need to understand where the error is thrown: https://www.educative.io/edpresso/how-to-resolve-the-javalangnullpointerexception

**Comment by Anik-Bardhan** [comment]
I am trying to fetch current related data from OSCAR, and also looking for ways to get the forecasted data (really stuck at this 👎🏼 ).
Thanks for the reply.  👍🏼

**Comment by seraphzl** [comment]
I download the OSCAR netCDF-4 data from https://podaac.jpl.nasa.gov/dataset/OSCAR_L4_OC_NRT_V2.0, and convert it to json using the command as above such as:
```
grib2json -d -c -n -o 20240423-surface-currents-oscar-0.25.json oscar_currents_nrt_20240423.nc
```
During the converting process, I get the error:
```
java.lang.NullPointerException
	at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:86)
	at net.nullschool.grib2json.Grib2Json.write(Grib2Json.java:117)
	at net.nullschool.grib2json.Launcher.main(Launcher.java:75)
```

I check the Line 86 of Grib2Json.java in src directory as:
```
        double depth = netcdfFile.findVariable("depth").readScalarDouble();
```
It seem to read and write the ```depth``` variable missing in the OSCAR nc file. Perhaps removing the ```depth``` variable can solve the problem?
