### ISSUE TITLE
How print the data for all the time forecast ? 

### ISSUE THREAD

**Issue by totomaze** [cambecc/grib2json#8]
Is it possible to print the data not only for the first forecast but for all the forecast contained in the grib file.
I have a grib file containing 7 days forecast every 3h.

Is there a way to extract them ?

Thanks and you did a great job.

**Comment by Anik-Bardhan** [comment]
Hey @totomaze. How did you get hold of the forecasted data? Been trying a lot to get that. Any reply will be of great help! Thank you. 👍🏼
