### ISSUE TITLE
[Error] - bin/java: not found

### ISSUE THREAD

**Issue by kylemclaren** [cambecc/grib2json#9]
I hate to open this issue because I know it has something to do with JAVA_HOME that I cannot figure out.

Trying to install on Ubuntu 14.04.

mvn build was successful

Out put of  `echo $JAVA_HOME` is `/usr/lib/jvm/java-7-openjdk-amd64/jre/bin/java`

Really hope you can point me in the right direction.

**Comment by jeremiak** [comment]
@kylemclaren Any chance you remember what you did to solve the issue? I'm having the same problem, and though I realize it isn't a specific `grib2json` issue I'd appreciate any help.

**Comment by kylemclaren** [comment]
@jeremiak 4 years ago so... zero chance I remember 😛 
 
But if you try using Docker with the official Maven image you should not have any trouble: `docker pull maven`
